partnerID: ""
partnerKey: ""

# 10.000 = 15
# 20.000 = 30
# ..
ratio:
  card: 1.5
  bank: 2

driver: "thesieure"

bank_transaction: false
bank-transaction-format: "locm-skyblock {name}"

commands:
  - "give %player% 1 1"

provider:
  type: "mongodb"
  host: "localhost"
  port: 27017